Add Razer Chroma HDK support to accessory driver
openrazer/openrazer pull request #1003
Opened 2020-01-23 02:08 UTC by CalcProgrammer1

Replaces PR https://github.com/openrazer/openrazer/pull/904

I reworked the HDK support into an accessory driver.

2020-01-23 17:58 UTC, z3ntu commented
Please run `./scripts/format_source.sh` to make the CI happy :)

Thanks for working on this!

2020-01-23 18:00 UTC, z3ntu commented on driver/razeraccessory_driver.c
> +    }
Can you make either one of the two options a `default` or add a printk as error and a return?

2020-01-23 18:03 UTC, z3ntu commented
Also do you have any plans on adding daemon support as well?
Also the HDK support a "how many strips are connected" command from what I know (@lah7 ?).
That one is class `00` and command `b5` with the parameters looking like the following:
```
    def parse_connected_strips(args):
        strip1 = args[2:4] == '10'
        strip2 = args[4:6] == '10'
        strip3 = args[6:8] == '10'
        strip4 = args[8:10] == '10'

        return ' (S1: {}, S2: {}, S3: {}, S4: {})'.format(strip1, strip2, strip3, strip4)
```
At least that's what it looks like from some pcaps I have :)

2020-01-27 06:38 UTC, CalcProgrammer1 commented
Updated my commit.  I tested it on Debian 10.  I added proper serial number reading for the HDK and left the existing fake serial for the mug.  I removed some of the mug specific device files from the HDK as well.  I did not yet implement the strips detect.  I attempted, but it would always read zeroes.

I'm not familiar with the daemon, I only use the kernel modules.  I'm not very fond of Python.

I also noticed the HDK has extra direction modes for the wave effect on Windows.  This driver doesn't support them yet as the existing wave function only supports left and right.  These work, but with the way I have my strips set up it's either expanding from the center or collapsing into the center.  In Synapse 3 I can also set left and right modes even with the strips facing apart from each other.

2020-01-28 00:23 UTC, lah7 commented
Thanks for adding support for this! I have the HDK too and things are working great. :+1: I've committed support for the daemon.

2020-01-28 01:34 UTC, CalcProgrammer1 commented
On your daemon commit shouldn't the matrix size be 4, 16 rather than 4, 15?

2020-01-28 02:50 UTC, CalcProgrammer1 commented
Added the HDK to the udev rules file and verified that I can access it as a standard user.

2020-01-28 09:33 UTC, lah7 commented
Good point on the matrix size, I got confused thinking it was base 0. It is 4 rows, 16 columns - confirmed working via the Python library.

2020-02-18 08:05 UTC, z3ntu commented on driver/razeraccessory_driver.c
> +        strncpy(&serial_string[0], &device->serial[0], 51);
Can you use `sizeof(serial_string)` instead of the hardcoded 51 here?

2020-02-18 08:08 UTC, z3ntu commented on driver/razeraccessory_driver.c
> +        }
For now this is fine, if more devices are added this'll likely be reworked to how it looks in other drivers

2020-02-18 08:08 UTC, z3ntu commented on daemon/openrazer_daemon/hardware/accessory.py
> +        "perspective_img": None
remove the lines with None please

2020-02-18 08:09 UTC, z3ntu commented on driver/razeraccessory_driver.c
> +    case USB_DEVICE_ID_RAZER_CHROMA_HDK:
keep the newline please ;)

2020-02-18 08:09 UTC, z3ntu requested changes
Aside from minor things this looks fine to me. Thank you for working on this!

2020-03-07 19:20 UTC, CalcProgrammer1 commented
@z3ntu This should be ready for re-review.

2020-03-12 13:48 UTC, lah7 approved these changes
I don't normally review driver code, but I'm confident this works perfectly (I've been using this). Thanks again!

2020-03-12 13:54 UTC, merged