Add support for Razer Viper Ultimate (#987)
openrazer/openrazer pull request #1034
Opened 2020-02-20 04:52 UTC by octopusSD

* Add support Razer Viper Ultimate - Wired (0x007A)
* Add support Razer Viper Ultimate - Wireless (0x007B)

Support for RGB charging dock (0x007E) not included.

2020-02-23 18:23 UTC, octopusSD commented
Linked to #987

2020-03-14 11:51 UTC, z3ntu requested changes
LGTM, just a small comment. Thanks for the PR!

2020-03-14 11:51 UTC, z3ntu commented on daemon/openrazer_daemon/hardware/mouse.py
> +class RazerViperUltimateWireless(__RazerDeviceBrightnessSuspend):
You can make this class inherit `RazerViperUltimateWired` and just overwrite the values that are different on the Wireless version (such as `USB_PID`, `EVENT_FILE_REGEX`, etc)

2020-04-06 19:42 UTC, z3ntu commented
Merged as 218bf33 . Thank you for the PR!

2020-04-06 19:42 UTC, closed without merging