Add support for Abyssus Elite (D.Va Edition)
openrazer/openrazer pull request #1067
Opened 2020-03-28 21:46 UTC by nightsky30

Add support for Abyssus Elite (D.Va Edition) for #900 

Everything has been tested including setting all effects, brightness, dpi, pollrate, and reading values.

2020-03-31 16:26 UTC, z3ntu requested changes
most comments from your other PR #1068 also apply here :)

2020-03-31 21:49 UTC, nightsky30 commented
@z3ntu The same changes have been incorporated into this PR, and retested.  This one should be good to go as well :+1:

2020-04-01 19:59 UTC, z3ntu commented on daemon/openrazer_daemon/hardware/mouse.py
> +        self.brightness = (_da_get_logo_brightness(self))
same comment as in the other PR ^^

2020-04-01 20:00 UTC, z3ntu commented
CI output:
> [!] driver/razermouse_driver.c does not respect the agreed coding style.
> You can run ./scripts/format_source.sh to automatically format those files.

2020-04-01 21:26 UTC, nightsky30 commented on daemon/openrazer_daemon/hardware/mouse.py
> +        self.brightness = (_da_get_logo_brightness(self))
Sorry about this.  Should be good now.

2020-04-05 09:45 UTC, z3ntu approved these changes
LGTM

2020-04-05 09:54 UTC, merged