implements brightness for anansi driver
openrazer/openrazer pull request #108
Opened 2016-12-08 04:40 UTC by Zerophase

So, I have the brightness settings working on the anansi. Should have the rest working in a little bit.

2016-12-21 09:33 UTC, terricain requested changes
Github aint letting me comment on razerkbd.c

Normally in `razer_attr_write_mode_none` we dont turn off game and macro led, we leave that to the daemon (though technically the daemon doesn't do that either ha (but it could...))

Line 642 `+ * Write device file "mode_reactive"?`
Is the `?` needed?

Line 988-993 seems like that shouldn't be there.
```c
+        case USB_DEVICE_ID_RAZER_BLADE_STEALTH:
+        case USB_DEVICE_ID_RAZER_BLADE_STEALTH_LATE_2016:
+            report = razer_chroma_misc_get_blade_brightness();
+            break;
+        
+  
```

Line 1000 is not needed as would fall though to default anyway.
```c
+        case USB_DEVICE_ID_RAZER_ANANSI:
```

2016-12-21 09:33 UTC, terrycain commented on driver/razerkbd_driver.h
> +    #define USB_DEVICE_ID_RAZER_ANANSI 0x010F
Put it in order of VID :wink: (and sort out any unordered ones too)

2016-12-21 09:33 UTC, terrycain commented on driver/razeranansicommon.c
> +{
This command technically isnt specific to the anansi... it just isnt used elsewhere. (its listed in the fw spec I have, it just listed without any description ha)

Replace with the following and put that in razerchromacommon.c, and the appropriate entry into razerchromacommon.h, then we have 1 less file.
```c
struct razer_report razer_chroma_standard_set_led_blinking_params(unsigned char variable_storage, unsigned char led_id)
{
	struct razer_report report = get_razer_report(0x03, 0x04, 0x04);
	report.arguments[0] = variable_storage; // Effect ID
	report.arguments[1] = led_id; // LED ID
	report.arguments[2] = 0x05;
	report.arguments[3] = 0x05;
	
	return report;
}
```


Where variable_storage would be one of the defines NOSTORE or VARSTORE and led_id should be MACRO_LED,

I have a feeling arg 2,3 could possibly be on and off timing.

2016-12-21 09:34 UTC, terrycain commented on driver/razeranansicommon.c
> +{
Obviously test it once its swapped out for this :wink:

2016-12-21 09:35 UTC, terrycain commented
Other than those changes, brilliant job mate. You tested the daemon right, either directly or via the python library or an app?

2016-12-21 23:11 UTC, Zerophase commented on driver/razeranansicommon.c
> +{
I'm trying to test by setting up a blinking device file, but for some reason it won't show up when I reload the driver. I set up a `DEVICE_ATTR`, and made sure to call `CREATE_DEVICE_FILE` and `device_remove_device`

2016-12-21 23:14 UTC, Zerophase commented on driver/razeranansicommon.c
> +{
This works for making the macro led blink as well. I tried changing argument 2, and the state of the macro led didn't change.

```c
struct razer_report report = get_razer_report(0x03, 0x04, 0x04);
report.arguments[0] = variable_storage;
report.arguments[1] = led_id;
report.arguments[2] = 0x05;
report.arguments[3] = 0x01;

```

2016-12-22 06:14 UTC, Zerophase commented
I believe everything meets your needs now.

2016-12-22 08:18 UTC, terrycain commented
All looks good, will have a proper look tonight but should be good to merge. Just to be sure, you tested it all right?

2016-12-22 08:22 UTC, Zerophase commented
Yeah, I tested everything manually.

2016-12-22 20:09 UTC, terricain approved these changes

2016-12-22 20:10 UTC, merged

2016-12-22 20:11 UTC, terrycain commented
:). If your up for it, see what [changing](https://github.com/Zerophase/razer-drivers/blob/b1357787917ec65821766fc7a753d15ebc232af9/driver/razerchromacommon.c#L91) the `0x05 0x05` to `0x02 0x02` does. I have a feeling it'll make it flash faster.

2016-12-23 07:57 UTC, Zerophase commented
It's about the same with either setting. Don't think it does anything for this keyboard at least.

2016-12-23 11:27 UTC, terrycain commented
Ahh np

2017-07-28 12:17 UTC, z3ntu commented
@Zerophase Can you please try the newest version of the driver if eg brightness still works? We have a report in #347 that says otherwise.

2017-07-30 22:02 UTC, Zerophase commented
Sure, just give me a sec.

2017-07-30 22:59 UTC, Zerophase commented
Yeah, it's not working currently. Going to have to dig around over the next couple days to see where the issue is. Looking at the old and current code I don't see any differences that could have broken it.