Add driver and daemon support for Razer BlackWidow X Ultimate
openrazer/openrazer pull request #110
Opened 2016-12-11 06:24 UTC by dfrankland

2016-12-11 10:19 UTC, terrycain commented
What options / effects can the keyboard do? your still missing alot.

2016-12-11 10:19 UTC, terricain requested changes

2016-12-11 10:19 UTC, terrycain commented on README.md
> +| Razer BlackWidow X Ultimate                   |  1532:0216  |   ✔    |   ✔    |
Should be 0217

2016-12-11 10:24 UTC, terricain approved these changes

2016-12-11 10:25 UTC, dfrankland commented
There aren't very many options on this keyboard. All it has are the per-key lighting options, recordable macros, and gaming mode.

As far as lights go there are really only these options, in green color, that are built in:
*   Brightness
*   Static On / Off
*   Starlight
*   Ripple
*   Breathe
*   Reactive
*   Wave

2016-12-11 20:06 UTC, terrycain commented
It can light up individual keys but technically they're only green right?

2016-12-11 20:19 UTC, dfrankland commented
Exactly.

2016-12-15 08:07 UTC, terrycain commented
Ok open an issue as we'll need to do some driver testing before we merge stuff.

2017-01-16 21:08 UTC, closed without merging