Viper (Ultimate) Cleanup
openrazer/openrazer pull request #1164
Opened 2020-06-05 10:39 UTC by nightsky30

The Viper and Viper Ultimate currently only generate device files and reports for breath, static, and none effects in the driver.

 - Cleaned up mouse.py by removing method references to spectrum, reactive, and wave effects.
 - Removed WAVE_DIRS, HAS_MATRIX, and MATRIX_DIMS as wave wasn't being used (is it supported??), and they only appear to have Logo LEDs.
 - Cleaned up fake drivers to reflect the current effect functionality in the driver.

**Note:** Viper and Viper Ultimate may support spectrum, reactive, and wave, but these were not fully implemented in the driver and presumably not tested.  Their smaller sibling the Viper Mini supports spectrum, reactive.

2020-06-06 16:18 UTC, troudbal commented
As a Viper mouse owner, I can tell that the spectrum and reactive effects are supported. I patched the driver and had no problem https://github.com/troudbal/openrazer/commit/80d55e781c11f8e73378e1f3b44d011ebc187717. As for the wave effect, I can't tell. It's not available in the windows driver.

2020-07-18 14:14 UTC, z3ntu reviewed
Tested on all affected devices?

2020-07-18 14:57 UTC, nightsky30 commented
> Tested on all affected devices?

See https://github.com/openrazer/openrazer/pull/1163/files#r456797607

2020-07-20 09:16 UTC, z3ntu commented on daemon/openrazer_daemon/hardware/mouse.py
> +               'set_logo_breath_random_naga_hex_v2', 'set_logo_breath_single_naga_hex_v2', 'set_logo_breath_dual_naga_hex_v2', ]
remove the comma near the end of the line

2020-07-20 09:17 UTC, z3ntu commented on daemon/openrazer_daemon/hardware/mouse.py
> +               'set_logo_breath_random_naga_hex_v2', 'set_logo_breath_single_naga_hex_v2', 'set_logo_breath_dual_naga_hex_v2', ]
same

2020-07-20 09:18 UTC, z3ntu requested changes
minor thing, LGTM otherwise

2020-07-29 15:27 UTC, Algram commented
I tested this with my Viper Ultimate and it seems the battery reporting is broken:
![image](https://user-images.githubusercontent.com/5053729/88819763-b5aa8a00-d1c0-11ea-8e71-0a20d44a23de.png)

2020-07-29 19:57 UTC, nightsky30 commented
@Algram Thanks! I added what was needed for the battery notifier. Can you verify everything is reading well? Battery status, effects, brightness, dpi, polling, firmware, serial? If not, we might need to experiment with different transaction IDs.

2020-07-29 20:36 UTC, Algram commented
@nightsky30 I tested it again: When connected the "getBattery" function returns a value like `8.627450980392156`. This could maybe be correct.

When wireless though the getBattery function still returns nothing unfortunately

2020-07-29 22:05 UTC, nightsky30 commented
@Algram That UNKNOWN can show up even when an entry is added in some cases. Are you seeing any values returned at all? And do you have a frontend to check with like RazerGenie?

The entries for the wireless receiver are already present, so I'm thinking this is a similar issue to what we've seen with the Lancehead Wireless, Mamba Wireless, Atheris, and Basilisk X HyperSpeed in that the mice read values inconsistently due to timing issues. And the wireless receivers need much longer wait times. Otherwise they would return values consistent with what you posted. Serial number would show as UNKNOWN, and firmware, battery, brightness, dpi, polling rate would all show as 0s.

Can you kindly pull the latest and retest? Fingers crossed :smile:

2020-07-30 06:22 UTC, Algram commented
@nightsky30 The UNKNOWN is gone and it reports the battery correctly when in wireless mode!

On the downside: In wired mode the battery now reports 0. This worked one commit before.

Thanks!

2020-07-30 08:06 UTC, nightsky30 commented
Ok, now it should only use the longer wait times for the wireless mode. Let me know if you see any reporting issues. :smile:

2020-07-30 14:16 UTC, Algram commented
@nightsky30 Still does not work for the wired mode for some reason..

2020-07-30 21:28 UTC, nightsky30 commented
> @nightsky30 Still does not work for the wired mode for some reason..

Ok, I think there are some intermittent timing issues with the Viper Ultimate similar to other recent wireless models. The fact that you are reading values SOME of the time is good! But I think the wired battery reporting once and then not a second time even after the timing for the wired device was reset to the original values shows it is only reporting properly part of the time.

I cannot definitively test and set the proper values as I do not own the device. Tweaking the timings is best left up to someone who physically has the mouse. They can either do some brute-force testing or perhaps capture packet traffic with wireshark and take a closer look at packet response times.

I'm inclined to open an issue for the wireless receiver for someone else to tackle, and leave that alone with regard to this clean up PR.

Again, the good news is that you are getting responses for battery, serial, etc showing those are working :)

2020-08-13 12:16 UTC, Algram commented
@nightsky30 Thanks for your help! As I own the device I would gladly try to brute force the correct timings. Could you give me a pointer to what pieces of code I would need to change in order to trial and error this?

2020-08-14 16:52 UTC, nightsky30 commented
@Algram That would be excellent!

You should only need to modify ```driver/razermouse_driver.h``` and ```driver/razermouse_driver.c```:

```driver/razermouse_driver.h```
https://github.com/openrazer/openrazer/blob/6c71ccfc2bbecc014bb13dd301b2b703ef75fcfa/driver/razermouse_driver.h#L68-L74

Here you can see the default WAIT values for mice:
```
RAZER_MOUSE_WAIT_MIN_US
RAZER_MOUSE_WAIT_MAX_US
```
As well as the special values for the newer wireless mice:
```
RAZER_NEW_MOUSE_RECEIVER_WAIT_MIN_US
RAZER_NEW_MOUSE_RECEIVER_WAIT_MAX_US
```
You may need to define new values specifically for the Viper Ultimate if it doesn't work with the \*_NEW_MOUSE_RECEIVER_WAIT_\* values.

```driver/razermouse_driver.c```
https://github.com/openrazer/openrazer/blob/7facc9429ab7e6711776a4eb8b3af520bf6ff0a8/driver/razermouse_driver.c#L43-L61

Modify razer_get_report so that it includes proper case statements for the Viper Ultimate wired and receiver devices. The device IDs for these should already be:

```
USB_DEVICE_ID_RAZER_VIPER_ULTIMATE_WIRED
USB_DEVICE_ID_RAZER_VIPER_ULTIMATE_WIRELESS
```

You may need a separate switch block that calls razer_get_usb_response with WAIT arguments specific to the Viper Ultimate if that device's times are different than those shared by the Mamba Wireless and Lancehead Wireless mice.

When I tested for the Lancehead Wireless, it took a while to get the proper wait values. It was very tedious. It might be more work up front, but easier to test in a VM with USB passthrough so you aren't repeatedly rebooting your bare metal box.

Change the WAIT values in razermouse_driver.h, build, install, reboot, test and see if everything reads properly.

When I tested, I would insert and remove the wireless USB dongle 15-20 times and keep track of how many times in a row settings would read properly. When I could remove and insert the device 15 times with it reliably reading all values, I considered it stable. If it failed at all, then I upped the values and started over (rebuild, reboot, etc).

Sometimes if the timings weren't high enough it might read only half the values reported in the frontend. The serial number might return, and the firmware might show, but perhaps some of the brightness values would display as 0 even though the lights were on. Sometimes the brightness might reflect accurately, but you may be missing the firmware version.

2020-09-06 13:38 UTC, z3ntu commented
Is still WIP? (based on the most recent comment)

2020-09-06 13:55 UTC, nightsky30 commented
> Is still WIP? (based on the most recent comment)

@z3ntu No, @ddavini helped test it in #1241. I consider this done and ready to merge.

2020-09-26 13:33 UTC, z3ntu approved these changes
LGTM, thanks a lot!

2020-09-26 13:33 UTC, merged