Add support for Razer Blade 15 Early 2020 base
openrazer/openrazer pull request #1171
Opened 2020-06-14 09:56 UTC by vvvrrooomm

2020-07-18 12:30 UTC, z3ntu approved these changes
LGTM, I've asked in #1150  for some testers so let's wait a bit before merging.

2020-08-16 04:37 UTC, zhassanbey requested changes
Fix device_type in ` case USB_DEVICE_ID_RAZER_BLADE_EARLY_2020_BASE:` line 415.

Could you also have a look at the issue I posted earlier after I tested this change, https://github.com/openrazer/openrazer/issues/1150#issuecomment-673903563

Thanks.

2020-08-16 04:37 UTC, zhassanbey commented on driver/razerkbd_driver.c
> +        device_type = "Razer Blade Stealth (Early 2020)\n";
Shouldn't that be `device_type = "Razer Blade 15 Base (Early 2020)\n"` instead?

2020-08-19 04:07 UTC, zhassanbey approved these changes

2020-09-14 16:33 UTC, FranciscodeMaussion commented
Sorry if is a bad place to post a question, but Idk how to test it, may i have to download and make it my self? Will this be merged to master soon? and to arch repositories?

2020-09-26 14:16 UTC, z3ntu commented
Thanks!

2020-09-26 14:16 UTC, merged