[WIP] Cleanup & rpm stuff
openrazer/openrazer pull request #126
Opened 2016-12-26 11:47 UTC by z3ntu

- [ ] Remove fedora scripts
- [ ] Remove upstart file
- [ ] Add rpm (fedora/opensuse) spec
- [ ] Replace manual python install with python setuputils

2016-12-26 19:19 UTC, terricain requested changes
Nice

2016-12-26 19:19 UTC, terrycain commented on rpm/razer-drivers.spec
> +#Source0: https://github.com/terrycain/razer-drivers/archive/v%{version}.tar.gz
Can we get that commented out version Source0 line working?

2016-12-26 19:19 UTC, terrycain commented on rpm/razer-drivers.spec
> +Requires: dbus-1-python3
Now that is a quuality package name

2016-12-26 19:19 UTC, terrycain commented on rpm/razer-drivers.spec
> +rm -rf $RPM_BUILD_ROOT/%{_datadir}/upstart/
PURGE TEH UPSTART :wink:

2016-12-29 00:28 UTC, terricain approved these changes
I still need to test the building of the rpms, but looks good.

2016-12-29 10:39 UTC, z3ntu commented
Please just try the spec file WITH this pr, otherwise some files are "unpackaged" and the build will just fail on opensuse tumbleweed 32bit ^^

2016-12-29 13:28 UTC, z3ntu commented
(something like this should be added to the website after this is merged, I can also transfer the repo to terry so he has full control over it and can revoke rights from me if needed 😉  )

## How to install on Fedora 25
```
sudo dnf config-manager --add-repo http://download.opensuse.org/repositories/home:z3ntu/Fedora_25/home:z3ntu.repo
sudo dnf install razer-drivers kernel-devel # be sure to include the kernel-devel package here, because Fedora has a problem with that package for at least 1.5 years
```

## How to install on OpenSUSE
Follow the instructions at https://software.opensuse.org/download.html?project=home%3Az3ntu&package=razer-drivers .

2016-12-29 13:39 UTC, z3ntu commented
Rebased (doesn't matter but still) and from new branch in #131

2016-12-29 13:39 UTC, closed without merging