WIP: Add support for Razer Kraken Kitty Edition
openrazer/openrazer pull request #1262
Opened 2020-09-21 22:23 UTC by 999eagle

This PR is still in progress. Helpful comments are very much appreciated.

This adds basic support for the Kraken Kitty Edition headset (see #949). The current state of this PR only implements the kernel driver module, no changes have been made to the daemon or library yet.

As the Kraken Kitty Edition for *some* reason uses the Chroma protocol instead of the protocol all other Kraken headsets use, I've decided to put the driver into a new kernel module called `razerkrakenchroma` to keep the code for the `razerkraken` module clean.

2020-09-26 14:00 UTC, z3ntu commented
Thanks for the PR! Please put the device into the razeraccessory driver though to avoid code duplication.

2020-09-26 15:35 UTC, 999eagle commented
Okay, I've moved everything into `razeraccessory`‌ now.

2020-09-26 16:54 UTC, z3ntu requested changes
just a few small things, looks good otherwise

2020-09-26 16:54 UTC, z3ntu commented on pylib/openrazer/_fake_driver/razerkrakenkittyedition.cfg
> +name = Razer Kraken Kitty Chroma Control
should be `Razer Kraken Kitty Edition`

2020-09-26 16:54 UTC, z3ntu commented on daemon/openrazer_daemon/hardware/headsets.py
> +    DEVICE_IMAGE = "https://assets3.razerzone.com/C2Ol5yRpYX8kE8JX3R9K2svFNaM=/1500x1000/https%3A%2F%2Fhybrismediaprod.blob.core.windows.net%2Fsys-master-phoenix-images-container%2Fhda%2Fh57%2F905545
Maybe use https://hybrismediaprod.blob.core.windows.net/sys-master-phoenix-images-container/hda/h57/9055450103838/Kraken-Kitty-Edition-Black-gallery-Hero.jpg directly; it's interesting how many different subdomains and media hosts Razer uses

2020-09-26 16:54 UTC, z3ntu commented on daemon/openrazer_daemon/hardware/headsets.py
> +        r'.*Razer_Kraken_Kitty_Chroma_Control-event-if00')
without the line break please

2020-10-02 10:37 UTC, tbaumann commented
Tested and works :+1:

2020-10-11 13:51 UTC, z3ntu approved these changes
LGTM, thanks a lot!

@tbaumann Thank you for testing!

2020-10-11 13:52 UTC, merged

2021-06-02 15:24 UTC, Kusoneko commented
Hello,

I would like to ask if any of you probed the device for support of the other Chroma effects besides None, Static and Breath (Single, Dual & Random) when adding support for the device, as I'm currently trying to figure out if it's possible to add the other effects or if I'm wasting my time trying to add support for them to the driver of this device.

Thank you,
Kusoneko

2021-06-20 08:43 UTC, z3ntu commented
@Kusoneko There's a PR for that now: #1528