Add support for the Ornata Chroma V2
openrazer/openrazer pull request #1372
Opened 2020-12-16 15:58 UTC by ShimmerGlass

Add support for the Ornata Chroma V2, based on existing keyboards.

What works :
* Effect "none"
* Effect "spectrum"
* Effect "wave"
* Effect "reactive"
* Effect "breath"
* Effect "starlight"
* Effect "static"
* Custom frame write and display
* Luminosity
* Game mode

What doesn't : 
* Effect "ripple" (doesn't seem implemented for other keyboards)

2020-12-18 16:27 UTC, Hellrazor1215 commented
I am very new at this....I download the files...not sure what to do with it
thank you for your great work!

2020-12-23 00:07 UTC, swedneck commented
Has anyone else been able to get this to work?

2020-12-23 13:38 UTC, Hellrazor1215 commented
@swedneck I have been trying for the last five days. With no luck so far.

2020-12-23 22:34 UTC, TermoZour commented
> @swedneck I have been trying for the last five days. With no luck so far.

What exactly have you been trying?

2020-12-24 16:53 UTC, Hellrazor1215 commented
@TermoZour I am trying to install the new driver for my keyboard

2020-12-24 17:01 UTC, TermoZour commented
> @TermoZour I am trying to install the new driver for my keyboard

Yes but what were the exact steps you've been trying? That's what I meant. All we know is you downloaded some files.

2020-12-24 23:53 UTC, Anty0 commented
Can confirm driver does work. Tested with RazerGenie, razerCommander and polychromatic.

Tested:
- Effect "none"
- Effect "spectrum"
- Effect "wave"
- Effect "reactive"
- Effect "breath"
- Effect "starlight"
- Effect "static"
- Luminosity

Doesn't work:
- Wave with direction to the left (only works direction to the right)

2020-12-25 02:55 UTC, nightsky30 commented
> * Wave with direction to the left (only works direction to the right)

It has been found that with the chroma extended matrix wave effect some devices use the wave left/right direction values `(0x00, 0x01)` while other use `(0x01, 0x02)`. If you tweak the direction values to `WAVE_DIRS = (1, 2)`, rebuild, etc, do both directions start working?

https://github.com/openrazer/openrazer/blob/9440bfee527d505010582bca8448a9bc87ad0e69/daemon/openrazer_daemon/hardware/keyboards.py#L618-L620

2020-12-25 03:19 UTC, Hellrazor1215 commented
Of course TermoZour, a read the Makefile and install (or I think I did). make daemon_install, make driver_install, make udev_install and make setup_dkms. Clean install as I try to install to a new linux MX-Linux installation. But that did not work. So I try installing the package from the repo and then use the command make driver_install. I did clean between my tries. Hope it clear enough, it is the first time I use git, please be patient.

2020-12-25 03:56 UTC, nightsky30 commented
@Hellrazor1215 I'm not familiar with MX Linux, but it seems to be Mepis/Debian based, as are Ubuntu/Mint. That being said, you could try the build instructions [here](https://github.com/openrazer/openrazer/wiki/Building-a-package#ubuntu--linux-mint). If the Ubuntu/Mint instructions don't work, you could also try the Debian instructions at the bottom of that page (very similar).

2020-12-25 21:49 UTC, swedneck commented
i'm on fedora 32 and i haven't been able to get it to work, building and installing the rpm just results in the keyboard not working at all until i remove the driver.

2020-12-26 17:28 UTC, sergeLabo commented
Work's on Debian 10

git clone -b ornata-chroma-v2 https://github.com/ShimmerGlass/openrazer.git
cd openrazer
sed -i '/linux-headers-generic/d' debian/control
./scripts/build_debs.sh
sudo dpkg -i ./dist/*.deb

Restart

2020-12-26 22:06 UTC, Hellrazor1215 commented
Thanks guys works great. followed sergeLabo instructions and notice that I was missing debhelper and python3-setuptools package. After installing these packages everything was fine and after a restart my keyboard was detected. Thanks again, now I have to find how to setup my own custom scheme.

2020-12-27 16:41 UTC, z3ntu requested changes
some minor things, LGTM otherwise

2020-12-27 16:41 UTC, z3ntu commented on README.md
> +| Razer Ornata Chroma V2                        |  1532:025D  |
Please sort by VID (put before Razer Cynosa V2)

2020-12-27 16:41 UTC, z3ntu commented on driver/razerkbd_driver.h
> +#define USB_DEVICE_ID_RAZER_ORNATA_CHROMA_V2 0x025D
sort by vid (put before USB_DEVICE_ID_RAZER_CYNOSA_V2)

2020-12-27 16:41 UTC, z3ntu commented on install_files/udev/99-razer.rules
> +ATTRS{idProduct}=="010d|010e|010f|0111|0113|011a|011b|0201|0202|0203|0204|0205|0207|0208|0209|020f|0210|0211|0214|0216|0217|021a|021e|021f|0220|0221|0224|0225|0226|0227|0228|022a|022b|022d|022f|0232|
put 025e before 025d (sort)

2020-12-27 16:44 UTC, swedneck commented
any ideas how to troubleshoot why this version's driver just makes my keyboard not send any input at all?

2020-12-27 23:39 UTC, Hellrazor1215 commented
> i'm on fedora 32 and i haven't been able to get it to work, building and installing the rpm just results in the keyboard not working at all until i remove the driver.

swedneck make sure there is no error when you compile, had the same problem on debian, some packages were needed to compile correctly.

2020-12-28 13:22 UTC, Anty0 commented
> > * Wave with direction to the left (only works direction to the right)
> 
> @Anty0 It has been found that with the chroma extended matrix wave effect some devices use the wave left/right direction values `(0x00, 0x01)` while other use `(0x01, 0x02)`. If you tweak the direction values to `WAVE_DIRS = (1, 2)`, rebuild, etc, do both directions start working for you?
> 
> https://github.com/openrazer/openrazer/blob/9440bfee527d505010582bca8448a9bc87ad0e69/daemon/openrazer_daemon/hardware/keyboards.py#L618-L620


Can confirm changing `WAVE_DIRS` as suggested by @nightsky30 fixes wave effect for me. Tested with polychromatic on [this](https://github.com/Anty0/openrazer/tree/ornata-chroma-v2) branch.

Just as a side note, for some reason the name of my keyboard (on the box) is Ornata V2 (without Chroma). (I'm not sure if there are more versions of this keyboard...)

2020-12-28 13:25 UTC, AtlasC0R3 commented
> Just as a side note, for some reason the name of my keyboard (on the box) is Ornata V2 (without Chroma). (I'm not sure if there are more versions of this keyboard...)
No, you aren't alone with this box. I think it's just the official box that has that name but the Synapse software on Windows has Ornata Chroma V2. _Probably because they couldn't fit it all on the box._

2020-12-29 10:31 UTC, swedneck commented
@Hellrazor1215 i can't see any errors when building the packages with `rpmbuild`

2020-12-29 18:10 UTC, ShimmerGlass commented
@z3ntu rebased and fixed the sorting issues
@nightsky30 changed WAVE_DIRS as suggested

2020-12-29 21:39 UTC, kevchu3 commented
> > > * Wave with direction to the left (only works direction to the right)
> > 
> > 
> > @Anty0 It has been found that with the chroma extended matrix wave effect some devices use the wave left/right direction values `(0x00, 0x01)` while other use `(0x01, 0x02)`. If you tweak the direction values to `WAVE_DIRS = (1, 2)`, rebuild, etc, do both directions start working for you?
> > https://github.com/openrazer/openrazer/blob/9440bfee527d505010582bca8448a9bc87ad0e69/daemon/openrazer_daemon/hardware/keyboards.py#L618-L620
> 
> Can confirm changing `WAVE_DIRS` as suggested by @nightsky30 fixes wave effect for me. Tested with polychromatic on [this](https://github.com/Anty0/openrazer/tree/ornata-chroma-v2) branch.
> 
> Just as a side note, for some reason the name of my keyboard (on the box) is Ornata V2 (without Chroma). (I'm not sure if there are more versions of this keyboard...)

I'm on Fedora 33 and pulled the latest changes (followed the wiki as usual) and it compiles.  Tested the waves in both directions on my Ornata v2, and they look fine to me.  Good work, @ShimmerGlass

2021-01-02 10:01 UTC, z3ntu approved these changes
LGTM, thanks!

2021-01-02 10:01 UTC, merged

2021-08-22 17:56 UTC, nyc-97 commented
I tried following sergeLabo's instructions and this doesn';t work for me. The ornata-chrome-v2 branch has been deleted. It says its supported on the website but Im not getting my keyboard recognized. my mouse and actual laptop keyboard is working fine though. Not sure whats going on.