Add support for Razer Blade Advanced 15 Mid 2021
openrazer/openrazer pull request #1561
Opened 2021-07-17 17:16 UTC by j-maynard

This is an initial commit to support the Razer Blade Advanced 15 Mid 2021 release.  This PR was tested on the 4k model of the Blade Advanced and I can confirm changing keyboard color and most profiles other than Startlight (random) seem to work.  I can't find the references to the logo to allow logo control to work.  If someone can point me in the right direction I might be able to fix that.

2021-07-17 18:47 UTC, j-maynard commented
Resolves #1542

2021-07-25 09:20 UTC, z3ntu commented on README.md
> +| Razer Blade 15 Advanced (Mid 2021)            |  1532:0276  |
Please put the device after `Razer Blade 15 Advanced (Early 2021)` so it's sorted by usb pid

2021-07-25 09:21 UTC, z3ntu commented on daemon/openrazer_daemon/hardware/keyboards.py
> +    Class for the Razer Blade 15 Advanced Mid (2021)
`Mid (2021)` -> `(Mid 2021)`

2021-07-25 09:21 UTC, z3ntu commented on driver/razerkbd_driver.h
> +#define USB_DEVICE_ID_RAZER_BLADE_15_ADV_MID_2021 0x0276
please move down below USB_DEVICE_ID_RAZER_BLADE_15_ADV_EARLY_2021 for sorting

2021-07-25 09:22 UTC, z3ntu commented on install_files/udev/99-razer.rules
> +ATTRS{idProduct}=="010d|010e|010f|0111|0113|011a|011b|011c|0201|0202|0203|0204|0205|0207|0208|0209|020f|0210|0211|0214|0216|0217|021a|021e|021f|0220|0221|0224|0225|0226|0227|0228|022a|022b|022c|022d|
move before 0a24 so it's sorted by pid

2021-07-25 09:24 UTC, z3ntu requested changes
A couple of minor comments

Regarding logo control, you have added 'get_logo_active' & 'set_logo_active' which are the functions used for controlling the logo. I'm currently not sure which frontends support this, but you can also open e.g. d-feet , session bus, org.razer, razer.device.lighting.logo setLogoActive and try it manually there.

2021-07-26 08:30 UTC, j-maynard commented
> Regarding logo control, you have added 'get_logo_active' & 'set_logo_active' which are the functions used for controlling the logo. I'm currently not sure which frontends support this, but you can also open e.g. d-feet , session bus, org.razer, razer.device.lighting.logo setLogoActive and try it manually there.

Thanks for the review... I've tested the logo and its all working and I've made the changes you asked for.  I only ask about the logo because Synapse has the option for a breathing logo.  I'm not sure if this is a new feature or a software implementation.

2021-08-01 09:40 UTC, z3ntu commented
Interesting. Would be interesting to have USB packet captures of Synapse doing that. Currently our code only has support for on/off for the logo I believe.

2021-08-05 09:27 UTC, julian9499 commented
Should that still be added or would this pull request suffice for now?

2021-08-05 19:59 UTC, j-maynard commented
I think if this pull request is all good we should maybe merge it and then take a look at the breathing logo effect.  I need to work out how to do packet capture for the Razer Thumderbolt Dock as well.  I can raise a seperate issue for the breathing logo so we can capture that as a thing.

2021-08-06 10:15 UTC, julian9499 commented
Yeah same thought although I have 0 experience with USB packets capturing I might look into the inner workings of the breathing logo a bit later.

2021-08-08 13:40 UTC, julian9499 commented
@z3ntu would this pull request suffice for now then?

2021-08-15 08:32 UTC, z3ntu approved these changes
LGTM, thank you for the pull request!

2021-08-15 08:34 UTC, merged