Added support for BlackWidow V3 Pro (Wired)
openrazer/openrazer pull request #1622
Opened 2021-09-28 02:18 UTC by GeoDoX

Fixes part of #1279

All credit goes to @faridgh1991 for his PR #1514

As the PR went stale, I decided it would be better to push the support for wired mode while wireless and bluetooth can be worked on in the future (something I'm going to try to do next).

To build and test
https://github.com/openrazer/openrazer/wiki/Building-a-package

2021-09-28 02:27 UTC, GeoDoX commented
Failing the check-formatting test, tried auto formatting but getting `xargs: astyle: No such file or directory`.

2021-09-28 05:10 UTC, IvanVojtko commented
I guess that wireless mode will be same as it is on my mini version. You can check my PR https://github.com/openrazer/openrazer/pull/1617. Basically you just need to use `9F` instead of `1F` in every packet.

2021-09-28 05:31 UTC, GeoDoX commented
@IvanVojtko For the pro in Wired mode, some packets are `3F` and some are `1F`. For the mini it seems they're all `1F` in wired mode. Don't wanna chance it till I can get some pcaps as I'm fairly new to deving for this. I'm open to a conversation about it though.

2021-09-28 20:30 UTC, EduardTheFirst commented
> Fixes #1619
> 
> All credit goes to @faridgh1991 for his PR #1514
> 
> As the PR went stale, I decided it would be better to push the support for wired mode while wireless and bluetooth can be worked on in the future (something I'm going to try to do next).
> 
> To build and test https://github.com/openrazer/openrazer/wiki/Building-a-package

hey do you have discord ? 
or telegram ?

2021-09-28 20:36 UTC, GeoDoX commented
@EduardTheFirst I am on the openrazer telegram. I also have discord geodox#1051

2021-10-03 19:58 UTC, GeoDoX commented
Don’t forget to comment back with your results of testing! It helps get this merged into official.

Positive and negative!

2021-10-04 20:52 UTC, EduardTheFirst commented
> @EduardTheFirst I am on the openrazer telegram. I also have discord geodox#1051

I have added you on discord but i haven't found you on telegram

2021-10-09 10:27 UTC, z3ntu requested changes

2021-10-09 10:27 UTC, z3ntu commented on install_files/udev/99-razer.rules
> +ATTRS{idProduct}=="010d|010e|010f|0111|0113|011a|011b|011c|0201|0202|0203|0204|0205|0207|0208|0209|020f|0210|0211|0214|0216|0217|021a|021e|021f|0220|0221|0224|0225|0226|0227|0228|022a|022b|022c|022d|
Please don't remove `0270|0271` from the list

2021-10-09 10:27 UTC, z3ntu commented on driver/razerkbd_driver.c
> -}
Is there any reason you're moving this function down? If not please keep it here (and add the others near this as well)

2021-10-09 10:27 UTC, z3ntu commented on README.md
> +| Razer BlackWidow V3 (Wired)                   |  1532:025A  |
Isn't this device the BlackWidow V3 Pro?

2021-10-09 10:27 UTC, z3ntu commented on daemon/openrazer_daemon/hardware/keyboards.py
> +    DEVICE_NAME = 'Razer BlackWidow V3 Pro Wired'
Pleases don't declare custom variables, and please use brackets around the "Wired"

2021-10-09 10:27 UTC, z3ntu commented on driver/razerkbd_driver.c
> +        device_type = "Razer BlackWidow V3 Pro(Wired)\n";
add a space before the bracket

2021-10-19 06:42 UTC, phl0 commented on README.md
> +| Razer BlackWidow V3 (Wired)                   |  1532:025A  |
VID/PID match my Black Window V3 Pro. So I think it should be renamed accordingly.

2021-10-19 13:49 UTC, Noah-Leick commented on README.md
> +| Razer BlackWidow V3 (Wired)                   |  1532:025A  |
@phl0 Pending review from z3ntu, the issue with naming is fixed with commit 484f51a74c822599182e61ce7b0a6aad1e857fa9.

2021-10-20 10:25 UTC, phl0 commented
I did test the current code of this PR/branch and it works. I can change colors on my Black Widow V3 pro. So besides the code beauty this would be nice to be merged upstream imho.

![DSC_2002](https://user-images.githubusercontent.com/7112907/138076495-659b3d94-0362-4694-899c-71609437a1bd.JPG)

![Screenshot from 2021-10-20 12-22-05](https://user-images.githubusercontent.com/7112907/138076512-eaa76cc0-b5dd-4198-adde-cc239ddecdc7.png)

2021-10-30 10:54 UTC, z3ntu commented
I've fixed up some things and rebased, can you please try the latest commit here again to see if I haven't broken anything?

2021-11-02 02:41 UTC, wyattearp commented
FYI - just another rando on the internet that's built this PR & tested successfully:

![image](https://user-images.githubusercontent.com/80254/139777879-7f58b831-1591-4bda-855f-22cb182c2b42.png)

Other notes:
- Ubuntu 20.04.3 LTS
- ./scripts/build_debs.sh used installation

2021-11-03 12:38 UTC, wyattearp commented
FYI - the only conflict I'm seeing on the merge is the fact that both the wired / wireless branches are stomping on the same spot in the code (because of course they are :) ).

```diff
diff --cc driver/razerkbd_driver.c
index 8903e56,c569ca0..0000000
--- a/driver/razerkbd_driver.c
+++ b/driver/razerkbd_driver.c
@@@ -853,8 -783,8 +865,13 @@@ static ssize_t razer_attr_read_device_t
          device_type = "Razer Huntsman Mini\n";
          break;
  
++<<<<<<< HEAD
 +    case USB_DEVICE_ID_RAZER_BLACKWIDOW_V3_PRO_WIRED:
 +        device_type = "Razer BlackWidow V3 Pro (Wired)\n";
++=======
+     case USB_DEVICE_ID_RAZER_BLACKWIDOW_V3:
+         device_type = "Razer BlackWidow V3\n";
++>>>>>>> master
          break;
  
```

Conflict 2:
```
diff --cc install_files/udev/99-razer.rules
index 0b3150a,9397c75..0000000
--- a/install_files/udev/99-razer.rules
+++ b/install_files/udev/99-razer.rules
@@@ -10,7 -10,7 +10,11 @@@ ATTRS{idProduct}=="0013|0016|0020|0024|
      ENV{ID_RAZER_CHROMA}="1", ENV{RAZER_DRIVER}="razermouse"
  
  # Keyboards
++<<<<<<< HEAD
 +ATTRS{idProduct}=="010d|010e|010f|0111|0113|011a|011b|011c|0201|0202|0203|0204|0205|0207|0208|0209|020f|0210|0211|0214|0216|0217|021a|021e|021f|0220|0221|0224|0225|0226|0227|0228|022a|022b|022c|022d|022f|0232|0233|0234|0235|0237|0239|023a|023b|023f|0240|0241|0243|0245|0246|024a|024c|024d|0252|0253|0255|0256|0257|0258|0259|025a|025d|025e|0266|026a|026d|0270|0271|0276|0279|0a24", \
++=======
+ ATTRS{idProduct}=="010d|010e|010f|0111|0113|011a|011b|011c|0201|0202|0203|0204|0205|0207|0208|0209|020f|0210|0211|0214|0216|0217|021a|021e|021f|0220|0221|0224|0225|0226|0227|0228|022a|022b|022c|022d|022f|0232|0233|0234|0235|0237|0239|023a|023b|023f|0240|0241|0243|0245|0246|024a|024c|024d|024e|0252|0253|0255|0256|0257|0258|0259|025d|025e|0266|026a|026d|0270|0271|0276|0279|0a24", \
++>>>>>>> master
```

Just don't forget the second `break;` in the driver and the addition of the second `ATTRS` line on the merge (because they're the same they get overlooked by both a rebase and a merge strategy).

2021-11-04 03:39 UTC, amurp commented
I see there are conflicts, but I'm dropping in to say this works for me once built:

![image](https://user-images.githubusercontent.com/6566097/140254140-f00b0439-732c-481c-a85f-a6913d6c5a86.png)

2021-11-05 23:14 UTC, eeyrjmr commented
working here as well 
![2021-11-05_23:12:59](https://user-images.githubusercontent.com/4564448/140588181-7352ba09-6bc0-41e4-96a8-4ac9eb5159f7.png)

Gentoo, wayland, clang

I had to refactor the gentoo ebuild (not just to use this PR but generally). That is a gentoo issue not openrazer/PR 

good job

2021-11-13 18:27 UTC, wyattearp commented
Bump - it's currently a very clean rebase/merge if you can hit

2021-11-15 20:01 UTC, charlydelta commented
Is there anything hindering the merge? What's the status? I'd really love to see this merged soon, please don't let this bit-rot again.

2021-12-03 17:49 UTC, z3ntu approved these changes
LGTM, thanks for fixing the remaining issues and to everyone for testing!

2021-12-03 17:50 UTC, merged