Add support for Razer Viper 8KHz
openrazer/openrazer pull request #1633
Opened 2021-10-09 18:06 UTC by openglfreak

Fixes #1426

2021-10-09 18:08 UTC, openglfreak commented
^ no code changes, I only changed the commit messages

2021-10-09 18:46 UTC, z3ntu commented
The poll rate *is* used by the daemon so support would very good but not strictly necessary for inclusion.

2021-10-09 18:57 UTC, openglfreak commented
I'll implement it if someone figures out which packets to send. I didn't figure that out with trial & error.

2021-10-10 15:29 UTC, openglfreak commented
Got it implemented, thanks to [this commit](https://github.com/sfroment/librazermacos/commit/74aac072ac7ee800cf53b439c459ae034a5b8c37#diff-f4e30a35643af9229934705075902f1b711153ce01d3c443b87b5d66314e412dR1018).

2021-10-10 15:41 UTC, openglfreak commented
Why is that commit marked as unverified it's literally signed with the same key as the one before it

2021-10-10 15:47 UTC, openglfreak commented
Looks like a bug, `git commit --amend --gpg-sign --reset-author` seems to only work correctly with `--no-edit`

2021-10-23 16:59 UTC, z3ntu requested changes
Looks pretty good, just one minor request right now.

2021-10-23 16:59 UTC, z3ntu commented on daemon/openrazer_daemon/dbus_services/dbus_methods/mamba.py
> +def set_poll_rate2(self, rate):
Please use a more descriptive name like `set_poll_rate_8k`

2021-10-23 16:59 UTC, z3ntu commented on daemon/openrazer_daemon/dbus_services/dbus_methods/mamba.py
> +def set_poll_rate2(self, rate):
Or even better, you can modify the original function to use `self.POLL_RATES` if available for checking.

2021-10-23 18:26 UTC, openglfreak commented on daemon/openrazer_daemon/dbus_services/dbus_methods/mamba.py
> +def set_poll_rate2(self, rate):
Yeah that's a much better solution, I implemented it in the new commit.

2021-10-30 11:19 UTC, z3ntu approved these changes
LGTM, thanks for the pull request!

2021-10-30 11:28 UTC, merged

2021-11-16 01:39 UTC, gaeldelameme commented
Hey! How can i install the code of Viper 8Khz?

2021-11-16 01:41 UTC, gaeldelameme commented
Hey, so I have to overwrite the source code to get the support for the viper 8Khz?

2021-11-16 09:42 UTC, lah7 commented
@gaeldelameme It depends on your distro. You can grab a copy of this repository and [build a package](https://github.com/openrazer/openrazer/wiki/Building-a-package). On Arch, install `openrazer-meta-git`, or on Ubuntu, add the `openrazer/daily` PPA.

2021-11-23 16:43 UTC, AlexanderCurl commented
> On Arch, install openrazer-meta-git.

I did, clean installed it, updated it, but no luck. I've used openrazer-meta-dkms-git also, still don't show my mouse.

2021-11-23 21:26 UTC, AlexanderCurl commented
Okay I tested with evhz on Arch linux, it's reporting only 1000Hz maximum, hence it's set to 8000Hz in polychromatic.

`Razer Razer Viper 8KHz: Latest   972Hz, Average   993Hz
Razer Razer Viper 8KHz: Latest   975Hz, Average   992Hz
Razer Razer Viper 8KHz: Latest  1024Hz, Average   993Hz
Razer Razer Viper 8KHz: Latest  1002Hz, Average   993Hz
Razer Razer Viper 8KHz: Latest   999Hz, Average   993Hz
Razer Razer Viper 8KHz: Latest   982Hz, Average   993Hz
Razer Razer Viper 8KHz: Latest  1019Hz, Average   993Hz
Razer Razer Viper 8KHz: Latest  1000Hz, Average   993Hz
Razer Razer Viper 8KHz: Latest   500Hz, Average   985Hz
Razer Razer Viper 8KHz: Latest   977Hz, Average   985Hz
Razer Razer Viper 8KHz: Latest  1022Hz, Average   985Hz
Razer Razer Viper 8KHz: Latest   495Hz, Average   977Hz
Razer Razer Viper 8KHz: Latest  1012Hz, Average   977Hz
Razer Razer Viper 8KHz: Latest   334Hz, Average   966Hz
Razer Razer Viper 8KHz: Latest   905Hz, Average   965Hz
Razer Razer Viper 8KHz: Latest   342Hz, Average   955Hz
Razer Razer Viper 8KHz: Latest   143Hz, Average   942Hz

Average for Razer Razer Viper 8KHz:   942Hz
`