Add support for Razer DeathAdder Essential (2021)
openrazer/openrazer pull request #1642
Opened 2021-10-14 12:56 UTC by KulkarniKaustubh

Adds support for Razer DeathAdder Essential with a new PID of 0098.
Fix #1566

2021-10-23 10:34 UTC, z3ntu requested changes
A few stylistic comments. Also can you confirm all the effects declared as supported actually work properly?

2021-10-23 10:34 UTC, z3ntu commented on README.md
> +| Razer DeathAdder Essential New                |  1532:0098  |
Please use the marketing name (probably written on the bottom of the device) in the code (you can leave the C define alone though), so presumably without the "New".

Also move this entry down so it's sorted by USB PID

2021-10-23 10:34 UTC, z3ntu commented on driver/razermouse_driver.h
> +#define USB_DEVICE_ID_RAZER_DEATHADDER_ESSENTIAL_NEW 0x0098
sort by value

2021-10-23 10:34 UTC, z3ntu commented on install_files/udev/99-razer.rules
> +ATTRS{idProduct}=="0013|0016|0020|0024|0025|002e|002f|0032|0034|0036|0037|0038|0039|0040|0041|0042|0043|0044|0045|0046|0048|004c|004f|0050|0053|0054|0059|005a|005b|005c|005e|0060|0062|0064|0065|0067|
sort by value

2021-10-23 10:41 UTC, KulkarniKaustubh commented on README.md
> +| Razer DeathAdder Essential New                |  1532:0098  |
> Please use the marketing name (probably written on the bottom of the device) in the code (you can leave the C define alone though), so presumably without the "New".
> 
> Also move this entry down so it's sorted by USB PID

Yes, I shall move it down so that it is sorted. The thing with the marketing name is that the name is "Razer DeathAdder Essential" itself, but with a different PID. The newer DeathAdder Essentials have a PID of 0098 and the older ones have a PID of 006E. Please do let me know what name I could use!

2021-10-30 09:07 UTC, z3ntu commented on README.md
> +| Razer DeathAdder Essential New                |  1532:0098  |
Then just use "Razer DeathAdder Essential", just the model names aren't very specific anyways

2021-10-30 11:20 UTC, KulkarniKaustubh commented on README.md
> +| Razer DeathAdder Essential New                |  1532:0098  |
Okay, I shall do that

2021-11-30 03:20 UTC, Etaash-mathamsetty commented
can you merge this, I have been using it for a month with no issues.

2021-12-04 09:57 UTC, z3ntu approved these changes
@Etaash-mathamsetty Thanks for confirming this works.

I've fixed up the rest as the PR author seems to be MIA, LGTM now!

2021-12-04 09:58 UTC, merged

2021-12-04 17:56 UTC, KulkarniKaustubh commented
> @Etaash-mathamsetty Thanks for confirming this works.
> 
> I've fixed up the rest as the PR author seems to be MIA, LGTM now!

I'm so sorry for being MIA! I had exams and could not make the appropriate changes. Thank you for taking the effort to do so, @z3ntu ! Hope I was able to contribute.

2021-12-07 02:16 UTC, Etaash-mathamsetty commented
The only effect that dosen't work is the scroll wheel brightness, logo brightness controls both. (might be an issue with polychromatic but I am not sure)

2021-12-07 10:16 UTC, lah7 commented
@Etaash-mathamsetty Try setting it directly using the Terminal, to be sure where the bug is:

    python3 -c "import openrazer.client as a; a.DeviceManager().devices[0].fx.misc.logo.brightness = 100"
    python3 -c "import openrazer.client as a; a.DeviceManager().devices[0].fx.misc.logo.brightness = 0"
    python3 -c "import openrazer.client as a; a.DeviceManager().devices[0].fx.misc.scroll.brightness = 100"
    python3 -c "import openrazer.client as a; a.DeviceManager().devices[0].fx.misc.scroll.brightness = 0"

(If you have multiple devices, you may need to increment the `0` to `1` in `devices[0]`)

2021-12-07 22:58 UTC, Etaash-mathamsetty commented
its a bug with polychromatic
openrazer says scroll is undefined

2021-12-08 10:56 UTC, lah7 commented
My mistake, it should be `scroll_wheel`, not `scroll`, please try again:

    python3 -c "import openrazer.client as a; a.DeviceManager().devices[0].fx.misc.scroll_wheel.brightness = 100"
    python3 -c "import openrazer.client as a; a.DeviceManager().devices[0].fx.misc.scroll_wheel.brightness = 0"

If it throws an error, paste it here. This test would actually imply a bug with OpenRazer (this device), not the frontend.

Equally, if it doesn't do anything or lights the wrong LED, it would need investigation and probably a conditional in the driver to use the correct protocol.

2021-12-08 23:53 UTC, Etaash-mathamsetty commented
> My mistake, it should be `scroll_wheel`, not `scroll`, please try again:
> 
> ```
> python3 -c "import openrazer.client as a; a.DeviceManager().devices[0].fx.misc.scroll_wheel.brightness = 100"
> python3 -c "import openrazer.client as a; a.DeviceManager().devices[0].fx.misc.scroll_wheel.brightness = 0"
> ```
> 
> If it throws an error, paste it here. This test would actually imply a bug with OpenRazer (this device), not the frontend.
> 
> Equally, if it doesn't do anything or lights the wrong LED, it would need investigation and probably a conditional in the driver to use the correct protocol.

yep doesn't do anything
either this mouse dosen't support scroll brightness 
or something changed on the hardware side for this mouse

2021-12-29 02:30 UTC, Etaash-mathamsetty commented
no scroll wheel brightness option in windows, can somebody remove it?

2021-12-29 08:58 UTC, z3ntu commented
Please continue this in a new issue.