Systemd dbus activation
openrazer/openrazer pull request #285
Opened 2017-05-19 14:45 UTC by hobarrera

This allows for the daemon to be auto-started via systemd--user whenever an application attempts to communicate to the dbus endpoints exposed by the daemon.

It also allows end-users to auto-start the daemon by simply running `systemd --user enable --now razer-daemon`.

2017-05-19 15:13 UTC, z3ntu approved these changes
What's the difference between a "dbus" systemd service vs a normal service?

But otherwise LGTM :)

2017-05-19 15:15 UTC, z3ntu commented
About the command you posted, I think it's s/systemd/systemctl/ 😉

2017-05-19 15:18 UTC, WhyNotHugo commented
(Keep in mind that I learnt most of this by inspecting existing services, rather than clear documentation).

* The dbus service (`org.razer.service`) tells dbus _"there's a systemd service that can answer `org.razer` interface called `razer-daemon.service`"_. If somebody comes knocking, start that service.
* The systemd service itself, actually runs the daemon. It can actually be started independently, (either by `systemctl --user start` or by enabling it to autostart via systemd.

(edit: systemd->systemctl by @z3ntu 😃)

2017-05-19 15:20 UTC, hobarrera commented
I edited the commit message on the last commit since it had the same mistake (systemd vs systemctl). Actual commit contents are the same.

2017-05-19 15:29 UTC, z3ntu commented
Breaks current makefiles:

```
Mai 19 17:28:57 g550jk systemd[921]: [/usr/lib/systemd/user/razer-daemon.service:8] Executable path is not absolute, ignoring: ##PREFIX#/bin/razer-service -Fv
Mai 19 17:28:57 g550jk systemd[921]: razer-daemon.service: Service lacks both ExecStart= and ExecStop= setting. Refusing.
```
Will look into it.

2017-05-19 15:31 UTC, hobarrera commented
@z3ntu Did you just copy the file over, or run the makefile? Note that the makefile replaces the `##PREFIX##`.

2017-05-19 15:32 UTC, z3ntu commented
Nah, running `make service` in the daemon/ directory produces the file:

```
[Unit]
Description=Daemon to manage razer devices in userspace
Documentation=man:razer-service(8)

[Service]
Type=dbus
BusName=org.razer
ExecStart=##PREFIX#/bin/razer-service -Fv

[Install]
WantedBy=default.target
```

2017-05-19 15:32 UTC, hobarrera commented
Darn, I missed  `#` there!

2017-05-19 15:32 UTC, z3ntu commented
:D Now I see it too

2017-05-19 15:33 UTC, hobarrera commented
Typo fixed.

2017-05-19 15:47 UTC, z3ntu commented
Confirmed working fine on KDE.

2017-05-19 15:56 UTC, z3ntu commented
So according to what I have found, the dbus service file gets used to start something when the dbus service is called (so basically "standby - and if something wants me, start").

(this part is written a bit later^^)
So if you stop the razer-daemon service and then just call the bus, the daemon autostarts 😲 (which is pretty cool)

2017-05-19 16:01 UTC, hobarrera commented
>  So if you stop the razer-daemon service and then just call the bus, the daemon autostarts 😲 (which is pretty cool)

Yup. That's how notification daemons usually work, and they always come back to life magically. :P

2017-05-19 20:08 UTC, z3ntu requested changes
Actually please rename the razer-daemon.service to razer-service.service because it's called razer-service and we would like to keep consistency :)

2017-05-20 03:17 UTC, hobarrera commented
I renamed it all to `razer.service`, but something doesn't convince me.

While I agree with consistency, maybe we can unify it all to `razer-daemon`? For one, I think having the systemd service run the razer-service already sounds a bit wierd. Also because it's a daemon. And finally because parts of the code (eg: the filenames) are already called it daemon. Would you agree with that?

2017-05-20 09:52 UTC, z3ntu commented
I agree but need the "approval" of @terrycain 😉

2017-05-20 09:52 UTC, terrycain commented
@z3ntu Approved

2017-05-20 09:53 UTC, z3ntu commented
Then also the executable razer-service has to be renamed razer-daemon :)

2017-05-20 10:02 UTC, z3ntu commented
I think I have all neccessary changes to rename razer-service to razer-daemon. I think pushing to master and then your PR on top would be the best solution.

2017-05-20 10:04 UTC, terrycain commented
@z3ntu 👍

2017-05-20 13:24 UTC, z3ntu commented
I have rebased your changes and pushed them [here](https://github.com/z3ntu/razer-drivers/tree/systemd-activation) temporarily.

2017-05-20 13:42 UTC, z3ntu commented
Okay I have managed to push the changes to your branch 👍 Should be working fine.

2017-05-20 17:32 UTC, hobarrera commented
LGTM. I squashed the last two commits since it didn't make sense to add so much noise pre-merge. :)

2017-05-20 18:01 UTC, z3ntu approved these changes

2017-06-14 19:39 UTC, hobarrera commented
Bump?  🙂

2017-06-15 20:50 UTC, terrycain commented
still need to test on ubuntu, but havent had the time mate. It is on my like lol

2017-06-25 13:35 UTC, merged

2017-06-25 15:05 UTC, hobarrera commented
🎉