Only allow daemon to be run as root if --as-root flag is passed
openrazer/openrazer pull request #482
Opened 2017-12-21 09:00 UTC by lezed1

https://trello.com/c/JjryMZdY/50-check-that-the-daemon-isnt-started-with-sudo

2017-12-21 09:04 UTC, z3ntu requested changes
Also please add the new flag to the man page

2017-12-21 09:04 UTC, z3ntu commented on daemon/run_openrazer_daemon.py
> +    parser.add_argument('--as-root', action='store_true', help='All the daemon to be started as root')
help text seems wrong

2017-12-21 09:05 UTC, z3ntu commented
And add the as-root flag to the file scripts/ci/launch-daemon.sh to fix the CI

2017-12-21 09:16 UTC, lezed1 commented
I didn't expect the new flag to be needed so quickly... All your feedback should be addressed!

2017-12-21 11:29 UTC, z3ntu commented
Thanks.

2017-12-21 11:32 UTC, z3ntu approved these changes
LGTM

2017-12-26 16:07 UTC, terricain approved these changes

2017-12-26 16:07 UTC, merged