New batch of Debian packaging fixes
openrazer/openrazer pull request #672
Opened 2018-09-08 08:29 UTC by daissi

Just a comment about architectures of "openrazer-kernel-modules-dkms" and "openrazer-daemon" these packages install only architecture-independent files (source code or python scripts). So, no need to specify an architecture excepted if I missed something :-)

2018-09-08 11:18 UTC, z3ntu requested changes
see comments

2018-09-08 11:18 UTC, z3ntu commented on debian/control
> + It auto-starts in the XDG directory and handles syncing across devices.
systemd user unit nowadays (except 16.04 where dbus-user-session is broken)

2018-09-08 11:18 UTC, z3ntu commented on install_files/appstream/io.github.openrazer.openrazer.metainfo.xml
> +    <modalias>usb:v1532p0F07d*</modalias>
script to generate this list? Updating by hand could be a bit annoying

2018-09-08 11:18 UTC, z3ntu commented on debian/control
> + the driver.
I'm not even sure if this package contains anything nowadays. Maybe check and if it's empty, either make it contain something or remove it?

2018-09-09 08:19 UTC, daissi commented on debian/control
> + the driver.
It was empty before my previous PR, now it contains scripts from the "examples" folder.
As this package is useless for the majority of people, we can decrease the relationship with the metapackage (from Depends to Recommends). I will do it in the next PR.

2018-09-09 08:25 UTC, daissi commented on install_files/appstream/io.github.openrazer.openrazer.metainfo.xml
> +    <modalias>usb:v1532p0F07d*</modalias>
Unfortunately, no script for that. This list is only useful (at the moment) to announce hardware support. If people are not aware about openrazer and they plug a razer compatible device, a software should propose to install openrazer. It could be useful to think to a method to generate this list and maybe also the one from the udev file.

2018-09-09 08:29 UTC, daissi commented
I have updated the description of openrazer-daemon debian package but if you have a better suggestion, I will be happy to update again.

2018-09-09 08:29 UTC, z3ntu requested changes
see comments

2018-09-09 08:29 UTC, z3ntu commented on debian/control
> + It contains a systemd user unit and an AppStream files.
either `an AppStream file` or `AppStream files`

2018-09-09 08:30 UTC, z3ntu commented on debian/control
> + the driver.
Sounds good.

2018-09-09 08:40 UTC, daissi commented on debian/control
> + It contains a systemd user unit and an AppStream files.
Fixed.

2018-09-09 08:42 UTC, z3ntu commented on install_files/appstream/io.github.openrazer.openrazer.metainfo.xml
> +    <modalias>usb:v1532p0F07d*</modalias>
This works:
```sh
grep -rh "USB_PID = " daemon/openrazer_daemon/hardware/ | cut -d '=' -f2 | grep -v None | sort -f | sed -E 's| 0x([0-9A-Fa-f]{4})|<modalias>usb:v1532p\1d*</modalias>|g'
```

2018-09-09 12:36 UTC, z3ntu approved these changes
LGTM

2018-09-09 12:36 UTC, merged