razer 2019 advanced
openrazer/openrazer pull request #773
Opened 2019-02-09 00:03 UTC by scramble45

Add 2019 Advance Razer Blade Support

- [x] Tested and this seems to work

2019-02-09 00:06 UTC, scramble45 commented
If anyone has the correct image files for this PR please link them here.

2019-02-12 16:08 UTC, scramble45 commented
@terrycain - can we get this merged in?

2019-02-13 00:42 UTC, Human commented
This is working for me. @scramble45 do no other effects work on this laptop?

2019-02-21 02:53 UTC, xkludge commented
I have been using @scramble45 branch for a week and appears to work as well

2019-02-26 17:34 UTC, scramble45 commented
if anything else needs to be done with this PR, someone let me know so we can get this merged in.

2019-03-19 09:59 UTC, z3ntu commented on README.md
> +| Razer Blade 15 (2019) Advanced                |  1532:023A  |
Please sort this by the USB IDs (so put this before the "Base Model" above

2019-03-19 10:03 UTC, z3ntu requested changes
See comments, otherwise looks good to me

2019-03-19 10:03 UTC, z3ntu commented on README.md
> +| Razer Blade 15 (2019) Advanced                |  1532:023A  |
Please sort this by the USB IDs (so put this before the "Base Model" above

2019-03-19 10:03 UTC, z3ntu commented on daemon/openrazer_daemon/hardware/keyboards.py
> +        r'.*BlackWidow_Ultimate_2016(-if01)?-event-kbd')
Please remove all the reformats that you didn't touch manually. (You maybe didn't use the max-line-length or whatever option with autopep8?)

2019-03-19 10:03 UTC, z3ntu commented on driver/razerkbd_driver.h
> +#endif
Put these lines above the 2018_BASE lines above (again, ordered by PID)

2019-03-19 10:03 UTC, z3ntu commented on install_files/appstream/io.github.openrazer.openrazer.metainfo.xml
> +    <modalias>usb:v1532p023ad*</modalias>
You can use a script in `scripts/` in the repo to generate this file, or , move the line manually one up

2019-03-19 10:03 UTC, z3ntu commented on install_files/udev/99-razer.rules
> +ATTRS{idProduct}=="010d|010e|0111|0113|011b|011a|010f|0201|0202|0203|0204|0205|0207|0208|0209|020f|0210|0211|0214|0216|021a|0217|021a|021e|021f|0220|0221|0224|0225|022a|022d|022f|0232|0233|023b|023a|
`023a` should be before `023b` again

2019-03-19 14:36 UTC, scramble45 commented
@z3ntu thanks for the review let me know if I missed anything.

2019-03-19 15:29 UTC, z3ntu approved these changes
LGTM (pushed a commit fixing two little style issues)

2019-03-19 15:34 UTC, scramble45 commented
@z3ntu thanks next time I will focus on sticking with your styling. I'm new to `autopep8`

2019-03-19 15:35 UTC, merged