Add support for Razer Huntsman
openrazer/openrazer pull request #792
Opened 2019-03-21 22:39 UTC by haze-sama

Based on @sumpster 's modification.

2019-03-21 22:40 UTC, terrycain commented
You also need to update https://github.com/openrazer/openrazer/blob/master/install_files/udev/99-razer.rules

2019-03-23 08:30 UTC, z3ntu commented
@haze-sama Did you test everything? Do all effects work properly?

2019-03-25 10:35 UTC, haze-sama commented
I only tested the color effects. 
The wave effect with left option doesn't work and I'm not sure, but it seems to me the slow and very slow option in reactive effect have the same duration.

2019-03-28 15:34 UTC, z3ntu commented
Does "Wave right" actually show a wave effect that's going to the right?

2019-04-14 10:19 UTC, haze-sama commented
Yes, "waves right" work correctly.

2019-05-07 12:05 UTC, Nag1bat0r commented
For me - work only color effect. Dont work Volume/Mute Next/Prev Track

2019-05-25 09:16 UTC, z3ntu commented
Please rebase on master.

2019-06-07 00:02 UTC, tommyjcarpenter commented
hey everyone, Is there a current barrier to merging this? Us hunstman's eagerly await! I globbed onto an issue (#739) today before I saw this, sorry!

2019-06-13 21:44 UTC, Nick-W commented
Also eagerly awaiting this to merge, huntsman elite support being added to repo packages would be very, very much appreciated.

2019-06-14 10:38 UTC, tommyjcarpenter commented
@Nick-W if I'm not mistaken this is only for the "regular" hunstman; huntsman elite PR was already closed I believe.

2019-06-16 08:08 UTC, z3ntu commented on daemon/openrazer_daemon/hardware/keyboards.py
> +    DEVICE_IMAGE = "https://d4kkpd69xt9l7.cloudfront.net/sys-master/root/h03/hd8/9016073224222/razer-huntsman-gallery01.jpg"
Please use https://assets.razerzone.com/eeimages/support/products/1360/1360_huntsman-3.png for this and the url below

2019-06-16 08:09 UTC, z3ntu commented on driver/razerkbd_driver.h
> +
Please fix this erroneous change

2019-06-16 08:10 UTC, z3ntu requested changes
See comments

2019-06-17 09:21 UTC, z3ntu commented
Please remove the `.vscode/ipch/315cbeb247cb7fb3/mmap_address.bin` file

2019-06-17 11:23 UTC, z3ntu commented
I'm still not sure if we should merge this with the wave effect to the left not working - or how we could fix that.

2019-06-22 15:51 UTC, ironLink21 commented
I've also been looking into this and I'm not able to get the Left Wave or Ripple to work.  I'm also not able to get anything with the FN key to work (volumn up/down/mute/kbd brightness(up/down)).  However you can control "brightness" & "gaming mode" via the client (polychromatic) so I'm wondering if it's just the FN key not being recognized which I've seen in the past with my laptop keyboard.
Running xev and watching the key presses those keys just come in as F1,F2,F3, etc.  When I run those same key combos from the laptop keyboard I get XF86AudioMute, XF86AudioLowerVolume, XF86AudioRaiseVolume.
Not sure how to get the actual key value for the FN key? That value is hard-coded in `razerkbd_driver.c:49` as `RAZER_FN 195` so maybe that's just a different value for the huntsman?

I agree with @z3ntu that this probably shouldn't get merged in just yet with those issues.

2019-06-22 18:11 UTC, tildearrow commented
The FN key shouldn't generate any key codes, because the driver doesn't map it to any key. I'd like to see the ability to enable the FN key (https://github.com/openrazer/openrazer/pull/635#issuecomment-504566705) though.

2019-07-04 01:56 UTC, nightsky30 commented
> I'm still not sure if we should merge this with the wave effect to the left not working - or how we could fix that.

With this device using values 0,1 for WAVE_DIRS I believe that is the issue identified with https://github.com/openrazer/openrazer/pull/833#issuecomment-507472890

2019-08-31 23:24 UTC, fionera commented
Any progress on this?

2019-09-16 21:19 UTC, cCurses commented
Any progress on this?

2019-12-03 11:46 UTC, Woundorf commented
What is required before merging this? Is something wrong still?

2019-12-09 12:18 UTC, pierrechopin commented
Should I install this from sources, or should I really wait for the merge ?

2019-12-25 10:40 UTC, MarkusZoppelt commented
> Should I install this from sources, or should I really wait for the merge ?

Interested in this as well. If there is no progress on this PR I will install from Zentetsu's source.

2019-12-28 18:30 UTC, craigccfl commented
Please add another one to this list waiting for pid# 1532-0227  Razer Huntsman to be added to supported devices. Appreciate all the work done for the community.

2020-01-05 17:51 UTC, z3ntu approved these changes
LGTM, thanks and sorry for the delay!

If there are still minor issues (wave?), please open an issue for those and we'll see that we can fix those in the future.

2020-01-05 17:58 UTC, merged