Add support for Razer Blade Pro (2019)
openrazer/openrazer pull request #916
Opened 2019-09-15 20:27 UTC by cawilliamson

Add support for the Razer Blade Pro (2019 edition) laptop.

I have verified that this builds and works properly.

2019-10-03 06:27 UTC, z3ntu commented on README.md
> +| Razer Blade Pro 17 (2019)                     |  1532:0234  |
Please move your entry a few places up so it's sorted by the VID:PID value

2019-10-03 06:28 UTC, z3ntu commented on driver/razerkbd_driver.h
> +#define USB_DEVICE_ID_RAZER_BLADE_PRO_2019 0x0234
Please move your device up after `USB_DEVICE_ID_RAZER_BLADE_2018` as well to have them sorted

2019-10-03 06:29 UTC, z3ntu commented on install_files/appstream/io.github.openrazer.openrazer.metainfo.xml
> +    <modalias>usb:v1532p0228e*</modalias>
This is wrong but you can just run `./scripts/generate_appstream_file.sh` to update this file

2019-10-03 06:30 UTC, z3ntu requested changes
In general LGTM, just a few comments.

Also does your Blade have an illuminated logo that can be switched on and off? If yes, please add support for that here.

2020-01-10 22:33 UTC, z3ntu commented
bump

2020-01-11 16:27 UTC, cawilliamson commented
I now returned my Razer Blade Pro unfortunately so don't have the device to hand to make any further amendments I'm afraid.

2020-01-11 19:29 UTC, legomind commented
I'll see what I can do when I get the time.

2020-01-29 11:35 UTC, ArchonMegalon commented
Wow, that is a shame that there is no support for the blade pro 2019. Is this basically dead now?

2020-02-24 11:48 UTC, z3ntu commented
@legomind @ArchonMegalon Please test this pull request, so it can get merged!

Instructions are at https://github.com/openrazer/openrazer/wiki/Building-a-package . If you have any questions, don't hesitate to ask!

2020-02-24 13:26 UTC, ArchonMegalon commented
That may be me, but - what is TARGET BRANCH in this case? 

Because https://github.com/openrazer/openrazer/tree/feature_bladepro2019 does not exist (anymore).

2020-02-24 14:27 UTC, z3ntu commented
@ArchonMegalon It exists now :wink:

2020-02-24 19:14 UTC, ArchonMegalon commented
Thank you. New to Razor. I just tried to install ubuntu (live testing it), but it seems I can only boot in safe graphics mode. Should i just install ubuntu in safe graphics? 

The screen in "normal" boot looks (and stays) like this:
![20200224_200713 (1)](https://user-images.githubusercontent.com/11421547/75183174-3d87f600-5742-11ea-9c84-4cd9fc36f387.jpg)

2020-02-25 01:00 UTC, legomind commented
How to test with Manjaro (ARCH)? I can build from AUR, but that wont have the changes in the test branch.

2020-02-25 01:42 UTC, legomind commented
Works great! No problems so far.

2020-02-25 10:08 UTC, ArchonMegalon commented
So, I think it works. The function keys are working, which is the most important thing for me. I also installed the Polychromatic Controller, but I get a "Device Not Recognised" message there. But I think I did install the wrong version of it, because I added the repository to dpkg and tried to install openrazor from there (because I am a dumb linux newbie). 

Anyway, I think apart from the chroma-think everything works - which is actually really impressive for me. 

As soon as the ID is in the main branch I guess the Poly-Controller will find it as well. Thanks for the work!

PS: IF you want me to test anything else, I am of course more than willing to do so. Just probably not able to do so without detailed instruction... :/

2020-03-14 12:43 UTC, z3ntu commented
Merged! Thanks for the testing!

2020-03-14 12:43 UTC, closed without merging